# Generated by Django 3.2.4 on 2021-06-08 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
