# Generated by Django 3.2.4 on 2021-06-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210609_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_key',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
